/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body70
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body70', ['BaseModel', Body70Model]);

    function Body70Model(BaseModel) {
        var Body70 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.page = this.getValue(obj.page);
            this.pageSize = this.getValue(obj.pageSize);
            this.numberType = this.getValue(obj.numberType);
            this.friendlyName = this.getValue(obj.friendlyName);
        };

        Body70.prototype = new BaseModel();
        Body70.prototype.constructor = Body70;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body70.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'page', realName: 'Page' },
                { name: 'pageSize', realName: 'PageSize' },
                { name: 'numberType', realName: 'NumberType' },
                { name: 'friendlyName', realName: 'FriendlyName' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body70.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Which page of the overall response will be returned. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body70.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body70.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body70.prototype.getPageSize = function () {
            return this.pageSize;
        };
    
        /**
         * Setter for PageSize
         * 
         * @param {int|null} value 
         */
        Body70.prototype.setPageSize = function (value) {
            this.pageSize = value;
        };
    
        /**
         * The capability supported by the number.Number type either SMS,Voice or all
         *
         * @return {NumberTypeEnum|null}
         */
        Body70.prototype.getNumberType = function () {
            return this.numberType;
        };
    
        /**
         * Setter for NumberType
         * 
         * @param {NumberTypeEnum|null} value 
         */
        Body70.prototype.setNumberType = function (value) {
            this.numberType = value;
        };
    
        /**
         * A human-readable label added to the number object.
         *
         * @return {string|null}
         */
        Body70.prototype.getFriendlyName = function () {
            return this.friendlyName;
        };
    
        /**
         * Setter for FriendlyName
         * 
         * @param {string|null} value 
         */
        Body70.prototype.setFriendlyName = function (value) {
            this.friendlyName = value;
        };
    
        return Body70;
    }

}(angular));
