/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body75
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body75', ['BaseModel', Body75Model]);

    function Body75Model(BaseModel) {
        var Body75 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.shortcode = this.getValue(obj.shortcode);
            this.friendlyName = this.getValue(obj.friendlyName);
            this.callbackMethod = this.getValue(obj.callbackMethod);
            this.callbackUrl = this.getValue(obj.callbackUrl);
            this.fallbackMethod = this.getValue(obj.fallbackMethod);
            this.fallbackUrl = this.getValue(obj.fallbackUrl);
        };

        Body75.prototype = new BaseModel();
        Body75.prototype.constructor = Body75;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body75.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'shortcode', realName: 'Shortcode' },
                { name: 'friendlyName', realName: 'FriendlyName' },
                { name: 'callbackMethod', realName: 'CallbackMethod' },
                { name: 'callbackUrl', realName: 'CallbackUrl' },
                { name: 'fallbackMethod', realName: 'FallbackMethod' },
                { name: 'fallbackUrl', realName: 'FallbackUrl' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body75.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * List of valid dedicated shortcode to your Ytel account.
         *
         * @return {string}
         */
        Body75.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string} value 
         */
        Body75.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        /**
         * User generated name of the dedicated shortcode.
         *
         * @return {string|null}
         */
        Body75.prototype.getFriendlyName = function () {
            return this.friendlyName;
        };
    
        /**
         * Setter for FriendlyName
         * 
         * @param {string|null} value 
         */
        Body75.prototype.setFriendlyName = function (value) {
            this.friendlyName = value;
        };
    
        /**
         * Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
         *
         * @return {string|null}
         */
        Body75.prototype.getCallbackMethod = function () {
            return this.callbackMethod;
        };
    
        /**
         * Setter for CallbackMethod
         * 
         * @param {string|null} value 
         */
        Body75.prototype.setCallbackMethod = function (value) {
            this.callbackMethod = value;
        };
    
        /**
         * URL that can be requested to receive notification when call has ended. A set of default parameters will
         * be sent here once the call is finished.
         *
         * @return {string|null}
         */
        Body75.prototype.getCallbackUrl = function () {
            return this.callbackUrl;
        };
    
        /**
         * Setter for CallbackUrl
         * 
         * @param {string|null} value 
         */
        Body75.prototype.setCallbackUrl = function (value) {
            this.callbackUrl = value;
        };
    
        /**
         * Specifies the HTTP method used to request the required FallbackUrl once call connects.
         *
         * @return {string|null}
         */
        Body75.prototype.getFallbackMethod = function () {
            return this.fallbackMethod;
        };
    
        /**
         * Setter for FallbackMethod
         * 
         * @param {string|null} value 
         */
        Body75.prototype.setFallbackMethod = function (value) {
            this.fallbackMethod = value;
        };
    
        /**
         * URL used if any errors occur during execution of InboundXML or at initial request of the required Url
         * provided with the POST.
         *
         * @return {string|null}
         */
        Body75.prototype.getFallbackUrl = function () {
            return this.fallbackUrl;
        };
    
        /**
         * Setter for FallbackUrl
         * 
         * @param {string|null} value 
         */
        Body75.prototype.setFallbackUrl = function (value) {
            this.fallbackUrl = value;
        };
    
        return Body75;
    }

}(angular));
