/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body36
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body36', ['BaseModel', Body36Model]);

    function Body36Model(BaseModel) {
        var Body36 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.date = this.getValue(obj.date);
        };

        Body36.prototype = new BaseModel();
        Body36.prototype.constructor = Body36;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body36.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'date', realName: 'Date' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body36.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Filter account information based on date.
         *
         * @return {string}
         */
        Body36.prototype.getDate = function () {
            return this.date;
        };
    
        /**
         * Setter for Date
         * 
         * @param {string} value 
         */
        Body36.prototype.setDate = function (value) {
            this.date = value;
        };
    
        return Body36;
    }

}(angular));
