/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body6
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body6', ['BaseModel', Body6Model]);

    function Body6Model(BaseModel) {
        var Body6 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.conferenceSid = this.getValue(obj.conferenceSid);
            this.participantSid = this.getValue(obj.participantSid);
            this.muted = this.getValue(obj.muted);
            this.deaf = this.getValue(obj.deaf);
        };

        Body6.prototype = new BaseModel();
        Body6.prototype.constructor = Body6;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body6.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'conferenceSid', realName: 'conferenceSid' },
                { name: 'participantSid', realName: 'ParticipantSid' },
                { name: 'muted', realName: 'Muted' },
                { name: 'deaf', realName: 'Deaf' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body6.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * ID of the active conference
         *
         * @return {string}
         */
        Body6.prototype.getConferenceSid = function () {
            return this.conferenceSid;
        };
    
        /**
         * Setter for ConferenceSid
         * 
         * @param {string} value 
         */
        Body6.prototype.setConferenceSid = function (value) {
            this.conferenceSid = value;
        };
    
        /**
         * ID of an active participant
         *
         * @return {string}
         */
        Body6.prototype.getParticipantSid = function () {
            return this.participantSid;
        };
    
        /**
         * Setter for ParticipantSid
         * 
         * @param {string} value 
         */
        Body6.prototype.setParticipantSid = function (value) {
            this.participantSid = value;
        };
    
        /**
         * Mute a participant
         *
         * @return {bool|null}
         */
        Body6.prototype.getMuted = function () {
            return this.muted;
        };
    
        /**
         * Setter for Muted
         * 
         * @param {bool|null} value 
         */
        Body6.prototype.setMuted = function (value) {
            this.muted = value;
        };
    
        /**
         * Make it so a participant cant hear
         *
         * @return {bool|null}
         */
        Body6.prototype.getDeaf = function () {
            return this.deaf;
        };
    
        /**
         * Setter for Deaf
         * 
         * @param {bool|null} value 
         */
        Body6.prototype.setDeaf = function (value) {
            this.deaf = value;
        };
    
        return Body6;
    }

}(angular));
