/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body57
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body57', ['BaseModel', Body57Model]);

    function Body57Model(BaseModel) {
        var Body57 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.conferenceSid = this.getValue(obj.conferenceSid);
            this.participantSid = this.getValue(obj.participantSid);
            this.audioUrl = this.getValue(obj.audioUrl);
        };

        Body57.prototype = new BaseModel();
        Body57.prototype.constructor = Body57;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body57.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'conferenceSid', realName: 'ConferenceSid' },
                { name: 'participantSid', realName: 'ParticipantSid' },
                { name: 'audioUrl', realName: 'AudioUrl' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body57.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a conference object.
         *
         * @return {string}
         */
        Body57.prototype.getConferenceSid = function () {
            return this.conferenceSid;
        };
    
        /**
         * Setter for ConferenceSid
         * 
         * @param {string} value 
         */
        Body57.prototype.setConferenceSid = function (value) {
            this.conferenceSid = value;
        };
    
        /**
         * The unique identifier for a participant object.
         *
         * @return {string}
         */
        Body57.prototype.getParticipantSid = function () {
            return this.participantSid;
        };
    
        /**
         * Setter for ParticipantSid
         * 
         * @param {string} value 
         */
        Body57.prototype.setParticipantSid = function (value) {
            this.participantSid = value;
        };
    
        /**
         * The URL for the audio file that is to be played during the conference. Multiple audio files can be
         * chained by using a semicolon.
         *
         * @return {AudioUrlEnum}
         */
        Body57.prototype.getAudioUrl = function () {
            return this.audioUrl;
        };
    
        /**
         * Setter for AudioUrl
         * 
         * @param {AudioUrlEnum} value 
         */
        Body57.prototype.setAudioUrl = function (value) {
            this.audioUrl = value;
        };
    
        return Body57;
    }

}(angular));
