/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body53
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body53', ['BaseModel', Body53Model]);

    function Body53Model(BaseModel) {
        var Body53 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.type = this.getValue(obj.type);
            this.page = this.getValue(obj.page);
            this.pagesize = this.getValue(obj.pagesize);
            this.shortcode = this.getValue(obj.shortcode);
        };

        Body53.prototype = new BaseModel();
        Body53.prototype.constructor = Body53;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body53.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'type', realName: 'type' },
                { name: 'page', realName: 'page' },
                { name: 'pagesize', realName: 'pagesize' },
                { name: 'shortcode', realName: 'Shortcode' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body53.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The type (category) of template Valid values: marketing, authorization
         *
         * @return {string|null}
         */
        Body53.prototype.getType = function () {
            return this.type;
        };
    
        /**
         * Setter for Type
         * 
         * @param {string|null} value 
         */
        Body53.prototype.setType = function (value) {
            this.type = value;
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body53.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body53.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * The count of objects to return per page.
         *
         * @return {int|null}
         */
        Body53.prototype.getPagesize = function () {
            return this.pagesize;
        };
    
        /**
         * Setter for Pagesize
         * 
         * @param {int|null} value 
         */
        Body53.prototype.setPagesize = function (value) {
            this.pagesize = value;
        };
    
        /**
         * Only list templates of type
         *
         * @return {string|null}
         */
        Body53.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string|null} value 
         */
        Body53.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        return Body53;
    }

}(angular));
