/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body34
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body34', ['BaseModel', Body34Model]);

    function Body34Model(BaseModel) {
        var Body34 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.subAccountSID = this.getValue(obj.subAccountSID);
            this.mergeNumber = this.getValue(obj.mergeNumber);
        };

        Body34.prototype = new BaseModel();
        Body34.prototype.constructor = Body34;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body34.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'subAccountSID', realName: 'SubAccountSID' },
                { name: 'mergeNumber', realName: 'MergeNumber' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body34.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The SubaccountSid to be deleted
         *
         * @return {string}
         */
        Body34.prototype.getSubAccountSID = function () {
            return this.subAccountSID;
        };
    
        /**
         * Setter for SubAccountSID
         * 
         * @param {string} value 
         */
        Body34.prototype.setSubAccountSID = function (value) {
            this.subAccountSID = value;
        };
    
        /**
         * 0 to delete or 1 to merge numbers to parent account.
         *
         * @return {MergeNumberEnum}
         */
        Body34.prototype.getMergeNumber = function () {
            return this.mergeNumber;
        };
    
        /**
         * Setter for MergeNumber
         * 
         * @param {MergeNumberEnum} value 
         */
        Body34.prototype.setMergeNumber = function (value) {
            this.mergeNumber = value;
        };
    
        return Body34;
    }

}(angular));
