/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body10
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body10', ['BaseModel', Body10Model]);

    function Body10Model(BaseModel) {
        var Body10 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.recordingSid = this.getValue(obj.recordingSid);
        };

        Body10.prototype = new BaseModel();
        Body10.prototype.constructor = Body10;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body10.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'recordingSid', realName: 'recordingSid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body10.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a recording object.
         *
         * @return {string}
         */
        Body10.prototype.getRecordingSid = function () {
            return this.recordingSid;
        };
    
        /**
         * Setter for RecordingSid
         * 
         * @param {string} value 
         */
        Body10.prototype.setRecordingSid = function (value) {
            this.recordingSid = value;
        };
    
        return Body10;
    }

}(angular));
