/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body4
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body4', ['BaseModel', Body4Model]);

    function Body4Model(BaseModel) {
        var Body4 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.page = this.getValue(obj.page);
            this.pageSize = this.getValue(obj.pageSize);
        };

        Body4.prototype = new BaseModel();
        Body4.prototype.constructor = Body4;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body4.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'page', realName: 'Page' },
                { name: 'pageSize', realName: 'PageSize' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body4.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body4.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body4.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * The count of objects to return per page.
         *
         * @return {int|null}
         */
        Body4.prototype.getPageSize = function () {
            return this.pageSize;
        };
    
        /**
         * Setter for PageSize
         * 
         * @param {int|null} value 
         */
        Body4.prototype.setPageSize = function (value) {
            this.pageSize = value;
        };
    
        return Body4;
    }

}(angular));
