/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body28
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body28', ['BaseModel', Body28Model]);

    function Body28Model(BaseModel) {
        var Body28 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.callSid = this.getValue(obj.callSid);
            this.url = this.getValue(obj.url);
            this.method = this.getValue(obj.method);
            this.status = this.getValue(obj.status);
        };

        Body28.prototype = new BaseModel();
        Body28.prototype.constructor = Body28;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body28.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'callSid', realName: 'CallSid' },
                { name: 'url', realName: 'Url' },
                { name: 'method', realName: 'Method' },
                { name: 'status', realName: 'Status' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body28.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for voice call that is in progress.
         *
         * @return {string}
         */
        Body28.prototype.getCallSid = function () {
            return this.callSid;
        };
    
        /**
         * Setter for CallSid
         * 
         * @param {string} value 
         */
        Body28.prototype.setCallSid = function (value) {
            this.callSid = value;
        };
    
        /**
         * URL the in-progress call will be redirected to
         *
         * @return {string|null}
         */
        Body28.prototype.getUrl = function () {
            return this.url;
        };
    
        /**
         * Setter for Url
         * 
         * @param {string|null} value 
         */
        Body28.prototype.setUrl = function (value) {
            this.url = value;
        };
    
        /**
         * The method used to request the above Url parameter
         *
         * @return {string|null}
         */
        Body28.prototype.getMethod = function () {
            return this.method;
        };
    
        /**
         * Setter for Method
         * 
         * @param {string|null} value 
         */
        Body28.prototype.setMethod = function (value) {
            this.method = value;
        };
    
        /**
         * Status to set the in-progress call to
         *
         * @return {Status1Enum|null}
         */
        Body28.prototype.getStatus = function () {
            return this.status;
        };
    
        /**
         * Setter for Status
         * 
         * @param {Status1Enum|null} value 
         */
        Body28.prototype.setStatus = function (value) {
            this.status = value;
        };
    
        return Body28;
    }

}(angular));
