/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body61
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body61', ['BaseModel', Body61Model]);

    function Body61Model(BaseModel) {
        var Body61 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.shortcode = this.getValue(obj.shortcode);
        };

        Body61.prototype = new BaseModel();
        Body61.prototype.constructor = Body61;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body61.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'shortcode', realName: 'Shortcode' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body61.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * List of valid Shortcode to your Ytel account
         *
         * @return {string}
         */
        Body61.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string} value 
         */
        Body61.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        return Body61;
    }

}(angular));
