/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body65
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body65', ['BaseModel', Body65Model]);

    function Body65Model(BaseModel) {
        var Body65 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.page = this.getValue(obj.page);
            this.pagesize = this.getValue(obj.pagesize);
            this.friendlyName = this.getValue(obj.friendlyName);
            this.dateCreated = this.getValue(obj.dateCreated);
        };

        Body65.prototype = new BaseModel();
        Body65.prototype.constructor = Body65;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body65.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'page', realName: 'page' },
                { name: 'pagesize', realName: 'pagesize' },
                { name: 'friendlyName', realName: 'FriendlyName' },
                { name: 'dateCreated', realName: 'DateCreated' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body65.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body65.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body65.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * Number of individual resources listed in the response per page
         *
         * @return {int|null}
         */
        Body65.prototype.getPagesize = function () {
            return this.pagesize;
        };
    
        /**
         * Setter for Pagesize
         * 
         * @param {int|null} value 
         */
        Body65.prototype.setPagesize = function (value) {
            this.pagesize = value;
        };
    
        /**
         * Only return conferences with the specified FriendlyName
         *
         * @return {string|null}
         */
        Body65.prototype.getFriendlyName = function () {
            return this.friendlyName;
        };
    
        /**
         * Setter for FriendlyName
         * 
         * @param {string|null} value 
         */
        Body65.prototype.setFriendlyName = function (value) {
            this.friendlyName = value;
        };
    
        /**
         * Conference created date
         *
         * @return {string|null}
         */
        Body65.prototype.getDateCreated = function () {
            return this.dateCreated;
        };
    
        /**
         * Setter for DateCreated
         * 
         * @param {string|null} value 
         */
        Body65.prototype.setDateCreated = function (value) {
            this.dateCreated = value;
        };
    
        return Body65;
    }

}(angular));
