/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body13
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body13', ['BaseModel', Body13Model]);

    function Body13Model(BaseModel) {
        var Body13 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.recordingsid = this.getValue(obj.recordingsid);
        };

        Body13.prototype = new BaseModel();
        Body13.prototype.constructor = Body13;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body13.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'recordingsid', realName: 'recordingsid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body13.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a recording.
         *
         * @return {string}
         */
        Body13.prototype.getRecordingsid = function () {
            return this.recordingsid;
        };
    
        /**
         * Setter for Recordingsid
         * 
         * @param {string} value 
         */
        Body13.prototype.setRecordingsid = function (value) {
            this.recordingsid = value;
        };
    
        return Body13;
    }

}(angular));
