/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body74
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body74', ['BaseModel', Body74Model]);

    function Body74Model(BaseModel) {
        var Body74 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.callSid = this.getValue(obj.callSid);
        };

        Body74.prototype = new BaseModel();
        Body74.prototype.constructor = Body74;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body74.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'callSid', realName: 'callSid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body74.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for the voice call.
         *
         * @return {string}
         */
        Body74.prototype.getCallSid = function () {
            return this.callSid;
        };
    
        /**
         * Setter for CallSid
         * 
         * @param {string} value 
         */
        Body74.prototype.setCallSid = function (value) {
            this.callSid = value;
        };
    
        return Body74;
    }

}(angular));
