/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body69
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body69', ['BaseModel', Body69Model]);

    function Body69Model(BaseModel) {
        var Body69 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.messageSid = this.getValue(obj.messageSid);
        };

        Body69.prototype = new BaseModel();
        Body69.prototype.constructor = Body69;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body69.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'messageSid', realName: 'MessageSid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body69.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a sms message.
         *
         * @return {string}
         */
        Body69.prototype.getMessageSid = function () {
            return this.messageSid;
        };
    
        /**
         * Setter for MessageSid
         * 
         * @param {string} value 
         */
        Body69.prototype.setMessageSid = function (value) {
            this.messageSid = value;
        };
    
        return Body69;
    }

}(angular));
