/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body7
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body7', ['BaseModel', Body7Model]);

    function Body7Model(BaseModel) {
        var Body7 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.conferenceSid = this.getValue(obj.conferenceSid);
            this.participantSid = this.getValue(obj.participantSid);
        };

        Body7.prototype = new BaseModel();
        Body7.prototype.constructor = Body7;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body7.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'conferenceSid', realName: 'ConferenceSid' },
                { name: 'participantSid', realName: 'ParticipantSid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body7.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a conference object.
         *
         * @return {string}
         */
        Body7.prototype.getConferenceSid = function () {
            return this.conferenceSid;
        };
    
        /**
         * Setter for ConferenceSid
         * 
         * @param {string} value 
         */
        Body7.prototype.setConferenceSid = function (value) {
            this.conferenceSid = value;
        };
    
        /**
         * The unique identifier for a participant object.
         *
         * @return {string}
         */
        Body7.prototype.getParticipantSid = function () {
            return this.participantSid;
        };
    
        /**
         * Setter for ParticipantSid
         * 
         * @param {string} value 
         */
        Body7.prototype.setParticipantSid = function (value) {
            this.participantSid = value;
        };
    
        return Body7;
    }

}(angular));
