/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body40
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body40', ['BaseModel', Body40Model]);

    function Body40Model(BaseModel) {
        var Body40 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.shortcode = this.getValue(obj.shortcode);
            this.to = this.getValue(obj.to);
            this.templateid = this.getValue(obj.templateid);
            this.data = this.getValue(obj.data);
            this.method = this.getValue(obj.method);
            this.messageStatusCallback = this.getValue(obj.messageStatusCallback);
        };

        Body40.prototype = new BaseModel();
        Body40.prototype.constructor = Body40;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body40.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'shortcode', realName: 'shortcode' },
                { name: 'to', realName: 'to' },
                { name: 'templateid', realName: 'templateid' },
                { name: 'data', realName: 'data' },
                { name: 'method', realName: 'Method' },
                { name: 'messageStatusCallback', realName: 'MessageStatusCallback' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body40.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The Short Code number that is the sender of this message
         *
         * @return {string}
         */
        Body40.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string} value 
         */
        Body40.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        /**
         * A valid 10-digit number that should receive the message
         *
         * @return {string}
         */
        Body40.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string} value 
         */
        Body40.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * The unique identifier for the template used for the message
         *
         * @return {uuid|string}
         */
        Body40.prototype.getTemplateid = function () {
            return this.templateid;
        };
    
        /**
         * Setter for Templateid
         * 
         * @param {uuid|string} value 
         */
        Body40.prototype.setTemplateid = function (value) {
            this.templateid = value;
        };
    
        /**
         * format of your data, example: {companyname}:test,{otpcode}:1234
         *
         * @return {string}
         */
        Body40.prototype.getData = function () {
            return this.data;
        };
    
        /**
         * Setter for Data
         * 
         * @param {string} value 
         */
        Body40.prototype.setData = function (value) {
            this.data = value;
        };
    
        /**
         * Specifies the HTTP method used to request the required URL once the Short Code message is sent.
         *
         * @return {string|null}
         */
        Body40.prototype.getMethod = function () {
            return this.method;
        };
    
        /**
         * Setter for Method
         * 
         * @param {string|null} value 
         */
        Body40.prototype.setMethod = function (value) {
            this.method = value;
        };
    
        /**
         * URL that can be requested to receive notification when Short Code message was sent.
         *
         * @return {string|null}
         */
        Body40.prototype.getMessageStatusCallback = function () {
            return this.messageStatusCallback;
        };
    
        /**
         * Setter for MessageStatusCallback
         * 
         * @param {string|null} value 
         */
        Body40.prototype.setMessageStatusCallback = function (value) {
            this.messageStatusCallback = value;
        };
    
        return Body40;
    }

}(angular));
