/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body12
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body12', ['BaseModel', Body12Model]);

    function Body12Model(BaseModel) {
        var Body12 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.recordingsid = this.getValue(obj.recordingsid);
        };

        Body12.prototype = new BaseModel();
        Body12.prototype.constructor = Body12;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body12.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'recordingsid', realName: 'recordingsid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body12.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for the recording.
         *
         * @return {string}
         */
        Body12.prototype.getRecordingsid = function () {
            return this.recordingsid;
        };
    
        /**
         * Setter for Recordingsid
         * 
         * @param {string} value 
         */
        Body12.prototype.setRecordingsid = function (value) {
            this.recordingsid = value;
        };
    
        return Body12;
    }

}(angular));
