/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body66
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body66', ['BaseModel', Body66Model]);

    function Body66Model(BaseModel) {
        var Body66 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.phonenumber = this.getValue(obj.phonenumber);
            this.fromaccountsid = this.getValue(obj.fromaccountsid);
            this.toaccountsid = this.getValue(obj.toaccountsid);
        };

        Body66.prototype = new BaseModel();
        Body66.prototype.constructor = Body66;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body66.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'phonenumber', realName: 'phonenumber' },
                { name: 'fromaccountsid', realName: 'fromaccountsid' },
                { name: 'toaccountsid', realName: 'toaccountsid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body66.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * A valid 10-digit Ytel number (E.164 format).
         *
         * @return {string}
         */
        Body66.prototype.getPhonenumber = function () {
            return this.phonenumber;
        };
    
        /**
         * Setter for Phonenumber
         * 
         * @param {string} value 
         */
        Body66.prototype.setPhonenumber = function (value) {
            this.phonenumber = value;
        };
    
        /**
         * A specific Accountsid from where Number is getting transfer.
         *
         * @return {string}
         */
        Body66.prototype.getFromaccountsid = function () {
            return this.fromaccountsid;
        };
    
        /**
         * Setter for Fromaccountsid
         * 
         * @param {string} value 
         */
        Body66.prototype.setFromaccountsid = function (value) {
            this.fromaccountsid = value;
        };
    
        /**
         * A specific Accountsid to which Number is getting transfer.
         *
         * @return {string}
         */
        Body66.prototype.getToaccountsid = function () {
            return this.toaccountsid;
        };
    
        /**
         * Setter for Toaccountsid
         * 
         * @param {string} value 
         */
        Body66.prototype.setToaccountsid = function (value) {
            this.toaccountsid = value;
        };
    
        return Body66;
    }

}(angular));
