/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body11
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body11', ['BaseModel', Body11Model]);

    function Body11Model(BaseModel) {
        var Body11 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.audiourl = this.getValue(obj.audiourl);
        };

        Body11.prototype = new BaseModel();
        Body11.prototype.constructor = Body11;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body11.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'audiourl', realName: 'audiourl' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body11.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * URL pointing to the location of the audio file that is to be transcribed.
         *
         * @return {string}
         */
        Body11.prototype.getAudiourl = function () {
            return this.audiourl;
        };
    
        /**
         * Setter for Audiourl
         * 
         * @param {string} value 
         */
        Body11.prototype.setAudiourl = function (value) {
            this.audiourl = value;
        };
    
        return Body11;
    }

}(angular));
