/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body45
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body45', ['BaseModel', Body45Model]);

    function Body45Model(BaseModel) {
        var Body45 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.phoneNumber = this.getValue(obj.phoneNumber);
        };

        Body45.prototype = new BaseModel();
        Body45.prototype.constructor = Body45;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body45.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'phoneNumber', realName: 'PhoneNumber' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body45.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * A valid 10-digit number (E.164 format).
         *
         * @return {string}
         */
        Body45.prototype.getPhoneNumber = function () {
            return this.phoneNumber;
        };
    
        /**
         * Setter for PhoneNumber
         * 
         * @param {string} value 
         */
        Body45.prototype.setPhoneNumber = function (value) {
            this.phoneNumber = value;
        };
    
        return Body45;
    }

}(angular));
