/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body38
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body38', ['BaseModel', Body38Model]);

    function Body38Model(BaseModel) {
        var Body38 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.shortcode = this.getValue(obj.shortcode);
            this.to = this.getValue(obj.to);
            this.dateSent = this.getValue(obj.dateSent);
            this.page = this.getValue(obj.page);
            this.pageSize = this.getValue(obj.pageSize);
        };

        Body38.prototype = new BaseModel();
        Body38.prototype.constructor = Body38;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body38.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'shortcode', realName: 'Shortcode' },
                { name: 'to', realName: 'To' },
                { name: 'dateSent', realName: 'DateSent' },
                { name: 'page', realName: 'Page' },
                { name: 'pageSize', realName: 'PageSize' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body38.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Only list messages sent from this Short Code
         *
         * @return {string|null}
         */
        Body38.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string|null} value 
         */
        Body38.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        /**
         * Only list messages sent to this number
         *
         * @return {string|null}
         */
        Body38.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string|null} value 
         */
        Body38.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * Only list messages sent with the specified date
         *
         * @return {string|null}
         */
        Body38.prototype.getDateSent = function () {
            return this.dateSent;
        };
    
        /**
         * Setter for DateSent
         * 
         * @param {string|null} value 
         */
        Body38.prototype.setDateSent = function (value) {
            this.dateSent = value;
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body38.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body38.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * The count of objects to return per page.
         *
         * @return {int|null}
         */
        Body38.prototype.getPageSize = function () {
            return this.pageSize;
        };
    
        /**
         * Setter for PageSize
         * 
         * @param {int|null} value 
         */
        Body38.prototype.setPageSize = function (value) {
            this.pageSize = value;
        };
    
        return Body38;
    }

}(angular));
