/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body', ['BaseModel', BodyModel]);

    function BodyModel(BaseModel) {
        var Body = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.from = this.getValue(obj.from);
            this.to = this.getValue(obj.to);
            this.url = this.getValue(obj.url);
            this.method = this.getValue(obj.method);
            this.statusCallBackUrl = this.getValue(obj.statusCallBackUrl);
            this.statusCallBackMethod = this.getValue(obj.statusCallBackMethod);
            this.fallBackUrl = this.getValue(obj.fallBackUrl);
            this.fallBackMethod = this.getValue(obj.fallBackMethod);
            this.heartBeatUrl = this.getValue(obj.heartBeatUrl);
            this.heartBeatMethod = this.getValue(obj.heartBeatMethod);
            this.timeout = this.getValue(obj.timeout);
            this.playDtmf = this.getValue(obj.playDtmf);
            this.hideCallerId = this.getValue(obj.hideCallerId);
            this.record = this.getValue(obj.record);
            this.recordCallBackUrl = this.getValue(obj.recordCallBackUrl);
            this.recordCallBackMethod = this.getValue(obj.recordCallBackMethod);
            this.transcribe = this.getValue(obj.transcribe);
            this.transcribeCallBackUrl = this.getValue(obj.transcribeCallBackUrl);
            this.ifMachine = this.getValue(obj.ifMachine);
            this.ifMachineUrl = this.getValue(obj.ifMachineUrl);
            this.ifMachineMethod = this.getValue(obj.ifMachineMethod);
            this.feedback = this.getValue(obj.feedback);
            this.surveyId = this.getValue(obj.surveyId);
        };

        Body.prototype = new BaseModel();
        Body.prototype.constructor = Body;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'from', realName: 'From' },
                { name: 'to', realName: 'To' },
                { name: 'url', realName: 'Url' },
                { name: 'method', realName: 'Method' },
                { name: 'statusCallBackUrl', realName: 'StatusCallBackUrl' },
                { name: 'statusCallBackMethod', realName: 'StatusCallBackMethod' },
                { name: 'fallBackUrl', realName: 'FallBackUrl' },
                { name: 'fallBackMethod', realName: 'FallBackMethod' },
                { name: 'heartBeatUrl', realName: 'HeartBeatUrl' },
                { name: 'heartBeatMethod', realName: 'HeartBeatMethod' },
                { name: 'timeout', realName: 'Timeout' },
                { name: 'playDtmf', realName: 'PlayDtmf' },
                { name: 'hideCallerId', realName: 'HideCallerId' },
                { name: 'record', realName: 'Record' },
                { name: 'recordCallBackUrl', realName: 'RecordCallBackUrl' },
                { name: 'recordCallBackMethod', realName: 'RecordCallBackMethod' },
                { name: 'transcribe', realName: 'Transcribe' },
                { name: 'transcribeCallBackUrl', realName: 'TranscribeCallBackUrl' },
                { name: 'ifMachine', realName: 'IfMachine' },
                { name: 'ifMachineUrl', realName: 'IfMachineUrl' },
                { name: 'ifMachineMethod', realName: 'IfMachineMethod' },
                { name: 'feedback', realName: 'Feedback' },
                { name: 'surveyId', realName: 'SurveyId' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * A valid Ytel Voice enabled number (E.164 format) that will be initiating the phone call.
         *
         * @return {string}
         */
        Body.prototype.getFrom = function () {
            return this.from;
        };
    
        /**
         * Setter for From
         * 
         * @param {string} value 
         */
        Body.prototype.setFrom = function (value) {
            this.from = value;
        };
    
        /**
         * To number
         *
         * @return {string}
         */
        Body.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string} value 
         */
        Body.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * URL requested once the call connects
         *
         * @return {string}
         */
        Body.prototype.getUrl = function () {
            return this.url;
        };
    
        /**
         * Setter for Url
         * 
         * @param {string} value 
         */
        Body.prototype.setUrl = function (value) {
            this.url = value;
        };
    
        /**
         * Specifies the HTTP method used to request the required URL once call connects.
         *
         * @return {string|null}
         */
        Body.prototype.getMethod = function () {
            return this.method;
        };
    
        /**
         * Setter for Method
         * 
         * @param {string|null} value 
         */
        Body.prototype.setMethod = function (value) {
            this.method = value;
        };
    
        /**
         * URL that can be requested to receive notification when call has ended. A set of default parameters will
         * be sent here once the call is finished.
         *
         * @return {string|null}
         */
        Body.prototype.getStatusCallBackUrl = function () {
            return this.statusCallBackUrl;
        };
    
        /**
         * Setter for StatusCallBackUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setStatusCallBackUrl = function (value) {
            this.statusCallBackUrl = value;
        };
    
        /**
         * Specifies the HTTP methodlinkclass used to request StatusCallbackUrl.
         *
         * @return {string|null}
         */
        Body.prototype.getStatusCallBackMethod = function () {
            return this.statusCallBackMethod;
        };
    
        /**
         * Setter for StatusCallBackMethod
         * 
         * @param {string|null} value 
         */
        Body.prototype.setStatusCallBackMethod = function (value) {
            this.statusCallBackMethod = value;
        };
    
        /**
         * URL requested if the initial Url parameter fails or encounters an error
         *
         * @return {string|null}
         */
        Body.prototype.getFallBackUrl = function () {
            return this.fallBackUrl;
        };
    
        /**
         * Setter for FallBackUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setFallBackUrl = function (value) {
            this.fallBackUrl = value;
        };
    
        /**
         * Specifies the HTTP method used to request the required FallbackUrl once call connects.
         *
         * @return {string|null}
         */
        Body.prototype.getFallBackMethod = function () {
            return this.fallBackMethod;
        };
    
        /**
         * Setter for FallBackMethod
         * 
         * @param {string|null} value 
         */
        Body.prototype.setFallBackMethod = function (value) {
            this.fallBackMethod = value;
        };
    
        /**
         * URL that can be requested every 60 seconds during the call to notify of elapsed tim
         *
         * @return {string|null}
         */
        Body.prototype.getHeartBeatUrl = function () {
            return this.heartBeatUrl;
        };
    
        /**
         * Setter for HeartBeatUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setHeartBeatUrl = function (value) {
            this.heartBeatUrl = value;
        };
    
        /**
         * Specifies the HTTP method used to request HeartbeatUrl.
         *
         * @return {string|null}
         */
        Body.prototype.getHeartBeatMethod = function () {
            return this.heartBeatMethod;
        };
    
        /**
         * Setter for HeartBeatMethod
         * 
         * @param {string|null} value 
         */
        Body.prototype.setHeartBeatMethod = function (value) {
            this.heartBeatMethod = value;
        };
    
        /**
         * Time (in seconds) Ytel should wait while the call is ringing before canceling the call
         *
         * @return {int|null}
         */
        Body.prototype.getTimeout = function () {
            return this.timeout;
        };
    
        /**
         * Setter for Timeout
         * 
         * @param {int|null} value 
         */
        Body.prototype.setTimeout = function (value) {
            this.timeout = value;
        };
    
        /**
         * DTMF Digits to play to the call once it connects. 0-9, #, or *
         *
         * @return {string|null}
         */
        Body.prototype.getPlayDtmf = function () {
            return this.playDtmf;
        };
    
        /**
         * Setter for PlayDtmf
         * 
         * @param {string|null} value 
         */
        Body.prototype.setPlayDtmf = function (value) {
            this.playDtmf = value;
        };
    
        /**
         * Specifies if the caller id will be hidden
         *
         * @return {bool|null}
         */
        Body.prototype.getHideCallerId = function () {
            return this.hideCallerId;
        };
    
        /**
         * Setter for HideCallerId
         * 
         * @param {bool|null} value 
         */
        Body.prototype.setHideCallerId = function (value) {
            this.hideCallerId = value;
        };
    
        /**
         * Specifies if the call should be recorded
         *
         * @return {bool|null}
         */
        Body.prototype.getRecord = function () {
            return this.record;
        };
    
        /**
         * Setter for Record
         * 
         * @param {bool|null} value 
         */
        Body.prototype.setRecord = function (value) {
            this.record = value;
        };
    
        /**
         * Recording parameters will be sent here upon completion
         *
         * @return {string|null}
         */
        Body.prototype.getRecordCallBackUrl = function () {
            return this.recordCallBackUrl;
        };
    
        /**
         * Setter for RecordCallBackUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setRecordCallBackUrl = function (value) {
            this.recordCallBackUrl = value;
        };
    
        /**
         * Method used to request the RecordCallback URL.
         *
         * @return {string|null}
         */
        Body.prototype.getRecordCallBackMethod = function () {
            return this.recordCallBackMethod;
        };
    
        /**
         * Setter for RecordCallBackMethod
         * 
         * @param {string|null} value 
         */
        Body.prototype.setRecordCallBackMethod = function (value) {
            this.recordCallBackMethod = value;
        };
    
        /**
         * Specifies if the call recording should be transcribed
         *
         * @return {bool|null}
         */
        Body.prototype.getTranscribe = function () {
            return this.transcribe;
        };
    
        /**
         * Setter for Transcribe
         * 
         * @param {bool|null} value 
         */
        Body.prototype.setTranscribe = function (value) {
            this.transcribe = value;
        };
    
        /**
         * Transcription parameters will be sent here upon completion
         *
         * @return {string|null}
         */
        Body.prototype.getTranscribeCallBackUrl = function () {
            return this.transcribeCallBackUrl;
        };
    
        /**
         * Setter for TranscribeCallBackUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setTranscribeCallBackUrl = function (value) {
            this.transcribeCallBackUrl = value;
        };
    
        /**
         * How Ytel should handle the receiving numbers voicemail machine
         *
         * @return {IfMachineEnum|null}
         */
        Body.prototype.getIfMachine = function () {
            return this.ifMachine;
        };
    
        /**
         * Setter for IfMachine
         * 
         * @param {IfMachineEnum|null} value 
         */
        Body.prototype.setIfMachine = function (value) {
            this.ifMachine = value;
        };
    
        /**
         * URL requested when IfMachine=continue
         *
         * @return {string|null}
         */
        Body.prototype.getIfMachineUrl = function () {
            return this.ifMachineUrl;
        };
    
        /**
         * Setter for IfMachineUrl
         * 
         * @param {string|null} value 
         */
        Body.prototype.setIfMachineUrl = function (value) {
            this.ifMachineUrl = value;
        };
    
        /**
         * Method used to request the IfMachineUrl.
         *
         * @return {string|null}
         */
        Body.prototype.getIfMachineMethod = function () {
            return this.ifMachineMethod;
        };
    
        /**
         * Setter for IfMachineMethod
         * 
         * @param {string|null} value 
         */
        Body.prototype.setIfMachineMethod = function (value) {
            this.ifMachineMethod = value;
        };
    
        /**
         * Specify if survey should be enable or not
         *
         * @return {bool|null}
         */
        Body.prototype.getFeedback = function () {
            return this.feedback;
        };
    
        /**
         * Setter for Feedback
         * 
         * @param {bool|null} value 
         */
        Body.prototype.setFeedback = function (value) {
            this.feedback = value;
        };
    
        /**
         * The unique identifier for the survey.
         *
         * @return {string|null}
         */
        Body.prototype.getSurveyId = function () {
            return this.surveyId;
        };
    
        /**
         * Setter for SurveyId
         * 
         * @param {string|null} value 
         */
        Body.prototype.setSurveyId = function (value) {
            this.surveyId = value;
        };
    
        return Body;
    }

}(angular));
