/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body49
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body49', ['BaseModel', Body49Model]);

    function Body49Model(BaseModel) {
        var Body49 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.productCode = this.getValue(obj.productCode);
            this.startDate = this.getValue(obj.startDate);
            this.endDate = this.getValue(obj.endDate);
            this.includeSubAccounts = this.getValue(obj.includeSubAccounts);
        };

        Body49.prototype = new BaseModel();
        Body49.prototype.constructor = Body49;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body49.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'productCode', realName: 'ProductCode' },
                { name: 'startDate', realName: 'startDate' },
                { name: 'endDate', realName: 'endDate' },
                { name: 'includeSubAccounts', realName: 'IncludeSubAccounts' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body49.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Filter usage results by product type.
         *
         * @return {ProductCodeEnum|null}
         */
        Body49.prototype.getProductCode = function () {
            return this.productCode;
        };
    
        /**
         * Setter for ProductCode
         * 
         * @param {ProductCodeEnum|null} value 
         */
        Body49.prototype.setProductCode = function (value) {
            this.productCode = value;
        };
    
        /**
         * Filter usage objects by start date.
         *
         * @return {string|null}
         */
        Body49.prototype.getStartDate = function () {
            return this.startDate;
        };
    
        /**
         * Setter for StartDate
         * 
         * @param {string|null} value 
         */
        Body49.prototype.setStartDate = function (value) {
            this.startDate = value;
        };
    
        /**
         * Filter usage objects by end date.
         *
         * @return {string|null}
         */
        Body49.prototype.getEndDate = function () {
            return this.endDate;
        };
    
        /**
         * Setter for EndDate
         * 
         * @param {string|null} value 
         */
        Body49.prototype.setEndDate = function (value) {
            this.endDate = value;
        };
    
        /**
         * Will include all subaccount usage data
         *
         * @return {string|null}
         */
        Body49.prototype.getIncludeSubAccounts = function () {
            return this.includeSubAccounts;
        };
    
        /**
         * Setter for IncludeSubAccounts
         * 
         * @param {string|null} value 
         */
        Body49.prototype.setIncludeSubAccounts = function (value) {
            this.includeSubAccounts = value;
        };
    
        return Body49;
    }

}(angular));
