/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body27
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body27', ['BaseModel', Body27Model]);

    function Body27Model(BaseModel) {
        var Body27 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.callSid = this.getValue(obj.callSid);
            this.playDtmf = this.getValue(obj.playDtmf);
            this.playDtmfDirection = this.getValue(obj.playDtmfDirection);
        };

        Body27.prototype = new BaseModel();
        Body27.prototype.constructor = Body27;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body27.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'callSid', realName: 'CallSid' },
                { name: 'playDtmf', realName: 'PlayDtmf' },
                { name: 'playDtmfDirection', realName: 'PlayDtmfDirection' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body27.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier of each call resource
         *
         * @return {string}
         */
        Body27.prototype.getCallSid = function () {
            return this.callSid;
        };
    
        /**
         * Setter for CallSid
         * 
         * @param {string} value 
         */
        Body27.prototype.setCallSid = function (value) {
            this.callSid = value;
        };
    
        /**
         * DTMF digits to play to the call. 0-9, #, *, W, or w
         *
         * @return {string}
         */
        Body27.prototype.getPlayDtmf = function () {
            return this.playDtmf;
        };
    
        /**
         * Setter for PlayDtmf
         * 
         * @param {string} value 
         */
        Body27.prototype.setPlayDtmf = function (value) {
            this.playDtmf = value;
        };
    
        /**
         * The leg of the call DTMF digits should be sent to
         *
         * @return {PlayDtmfDirectionEnum|null}
         */
        Body27.prototype.getPlayDtmfDirection = function () {
            return this.playDtmfDirection;
        };
    
        /**
         * Setter for PlayDtmfDirection
         * 
         * @param {PlayDtmfDirectionEnum|null} value 
         */
        Body27.prototype.setPlayDtmfDirection = function (value) {
            this.playDtmfDirection = value;
        };
    
        return Body27;
    }

}(angular));
