/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body5
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body5', ['BaseModel', Body5Model]);

    function Body5Model(BaseModel) {
        var Body5 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.numbertype = this.getValue(obj.numbertype);
            this.areacode = this.getValue(obj.areacode);
            this.pagesize = this.getValue(obj.pagesize);
        };

        Body5.prototype = new BaseModel();
        Body5.prototype.constructor = Body5;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body5.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'numbertype', realName: 'numbertype' },
                { name: 'areacode', realName: 'areacode' },
                { name: 'pagesize', realName: 'pagesize' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body5.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Number type either SMS,Voice or all
         *
         * @return {Numbertype1Enum}
         */
        Body5.prototype.getNumbertype = function () {
            return this.numbertype;
        };
    
        /**
         * Setter for Numbertype
         * 
         * @param {Numbertype1Enum} value 
         */
        Body5.prototype.setNumbertype = function (value) {
            this.numbertype = value;
        };
    
        /**
         * Specifies the area code for the returned list of available numbers. Only available for North American
         * numbers.
         *
         * @return {string}
         */
        Body5.prototype.getAreacode = function () {
            return this.areacode;
        };
    
        /**
         * Setter for Areacode
         * 
         * @param {string} value 
         */
        Body5.prototype.setAreacode = function (value) {
            this.areacode = value;
        };
    
        /**
         * The count of objects to return.
         *
         * @return {int|null}
         */
        Body5.prototype.getPagesize = function () {
            return this.pagesize;
        };
    
        /**
         * Setter for Pagesize
         * 
         * @param {int|null} value 
         */
        Body5.prototype.setPagesize = function (value) {
            this.pagesize = value;
        };
    
        return Body5;
    }

}(angular));
