/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body46
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body46', ['BaseModel', Body46Model]);

    function Body46Model(BaseModel) {
        var Body46 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.callsid = this.getValue(obj.callsid);
        };

        Body46.prototype = new BaseModel();
        Body46.prototype.constructor = Body46;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body46.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'callsid', realName: 'callsid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body46.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for the voice call.
         *
         * @return {string}
         */
        Body46.prototype.getCallsid = function () {
            return this.callsid;
        };
    
        /**
         * Setter for Callsid
         * 
         * @param {string} value 
         */
        Body46.prototype.setCallsid = function (value) {
            this.callsid = value;
        };
    
        return Body46;
    }

}(angular));
