/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body72
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body72', ['BaseModel', Body72Model]);

    function Body72Model(BaseModel) {
        var Body72 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.phonenumber = this.getValue(obj.phonenumber);
        };

        Body72.prototype = new BaseModel();
        Body72.prototype.constructor = Body72;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body72.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'phonenumber', realName: 'Phonenumber' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body72.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Specifies the multiple phone numbers for check updated spamscore .
         *
         * @return {string}
         */
        Body72.prototype.getPhonenumber = function () {
            return this.phonenumber;
        };
    
        /**
         * Setter for Phonenumber
         * 
         * @param {string} value 
         */
        Body72.prototype.setPhonenumber = function (value) {
            this.phonenumber = value;
        };
    
        return Body72;
    }

}(angular));
