/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body76
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body76', ['BaseModel', Body76Model]);

    function Body76Model(BaseModel) {
        var Body76 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.shortcode = this.getValue(obj.shortcode);
            this.page = this.getValue(obj.page);
            this.pagesize = this.getValue(obj.pagesize);
        };

        Body76.prototype = new BaseModel();
        Body76.prototype.constructor = Body76;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body76.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'shortcode', realName: 'Shortcode' },
                { name: 'page', realName: 'page' },
                { name: 'pagesize', realName: 'pagesize' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body76.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * Only list Short Code Assignment sent from this Short Code
         *
         * @return {string|null}
         */
        Body76.prototype.getShortcode = function () {
            return this.shortcode;
        };
    
        /**
         * Setter for Shortcode
         * 
         * @param {string|null} value 
         */
        Body76.prototype.setShortcode = function (value) {
            this.shortcode = value;
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {string|null}
         */
        Body76.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {string|null} value 
         */
        Body76.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * The count of objects to return per page.
         *
         * @return {string|null}
         */
        Body76.prototype.getPagesize = function () {
            return this.pagesize;
        };
    
        /**
         * Setter for Pagesize
         * 
         * @param {string|null} value 
         */
        Body76.prototype.setPagesize = function (value) {
            this.pagesize = value;
        };
    
        return Body76;
    }

}(angular));
