/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body59
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body59', ['BaseModel', Body59Model]);

    function Body59Model(BaseModel) {
        var Body59 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.keywordid = this.getValue(obj.keywordid);
        };

        Body59.prototype = new BaseModel();
        Body59.prototype.constructor = Body59;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body59.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'keywordid', realName: 'Keywordid' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body59.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier of each keyword
         *
         * @return {string}
         */
        Body59.prototype.getKeywordid = function () {
            return this.keywordid;
        };
    
        /**
         * Setter for Keywordid
         * 
         * @param {string} value 
         */
        Body59.prototype.setKeywordid = function (value) {
            this.keywordid = value;
        };
    
        return Body59;
    }

}(angular));
