/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body51
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body51', ['BaseModel', Body51Model]);

    function Body51Model(BaseModel) {
        var Body51 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.conferenceSid = this.getValue(obj.conferenceSid);
            this.participantNumber = this.getValue(obj.participantNumber);
            this.muted = this.getValue(obj.muted);
            this.deaf = this.getValue(obj.deaf);
        };

        Body51.prototype = new BaseModel();
        Body51.prototype.constructor = Body51;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body51.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'conferenceSid', realName: 'ConferenceSid' },
                { name: 'participantNumber', realName: 'ParticipantNumber' },
                { name: 'muted', realName: 'Muted' },
                { name: 'deaf', realName: 'Deaf' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body51.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a conference object.
         *
         * @return {string}
         */
        Body51.prototype.getConferenceSid = function () {
            return this.conferenceSid;
        };
    
        /**
         * Setter for ConferenceSid
         * 
         * @param {string} value 
         */
        Body51.prototype.setConferenceSid = function (value) {
            this.conferenceSid = value;
        };
    
        /**
         * The phone number of the participant to be added.
         *
         * @return {string}
         */
        Body51.prototype.getParticipantNumber = function () {
            return this.participantNumber;
        };
    
        /**
         * Setter for ParticipantNumber
         * 
         * @param {string} value 
         */
        Body51.prototype.setParticipantNumber = function (value) {
            this.participantNumber = value;
        };
    
        /**
         * Specifies if participant should be muted.
         *
         * @return {bool|null}
         */
        Body51.prototype.getMuted = function () {
            return this.muted;
        };
    
        /**
         * Setter for Muted
         * 
         * @param {bool|null} value 
         */
        Body51.prototype.setMuted = function (value) {
            this.muted = value;
        };
    
        /**
         * Specifies if the participant should hear audio in the conference.
         *
         * @return {bool|null}
         */
        Body51.prototype.getDeaf = function () {
            return this.deaf;
        };
    
        /**
         * Setter for Deaf
         * 
         * @param {bool|null} value 
         */
        Body51.prototype.setDeaf = function (value) {
            this.deaf = value;
        };
    
        return Body51;
    }

}(angular));
