/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body42
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body42', ['BaseModel', Body42Model]);

    function Body42Model(BaseModel) {
        var Body42 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.page = this.getValue(obj.page);
            this.pageSize = this.getValue(obj.pageSize);
            this.to = this.getValue(obj.to);
            this.from = this.getValue(obj.from);
            this.dateCreated = this.getValue(obj.dateCreated);
        };

        Body42.prototype = new BaseModel();
        Body42.prototype.constructor = Body42;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body42.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'page', realName: 'Page' },
                { name: 'pageSize', realName: 'PageSize' },
                { name: 'to', realName: 'To' },
                { name: 'from', realName: 'From' },
                { name: 'dateCreated', realName: 'DateCreated' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body42.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
         *
         * @return {int|null}
         */
        Body42.prototype.getPage = function () {
            return this.page;
        };
    
        /**
         * Setter for Page
         * 
         * @param {int|null} value 
         */
        Body42.prototype.setPage = function (value) {
            this.page = value;
        };
    
        /**
         * Number of individual resources listed in the response per page
         *
         * @return {int|null}
         */
        Body42.prototype.getPageSize = function () {
            return this.pageSize;
        };
    
        /**
         * Setter for PageSize
         * 
         * @param {int|null} value 
         */
        Body42.prototype.setPageSize = function (value) {
            this.pageSize = value;
        };
    
        /**
         * Filter calls that were sent to this 10-digit number (E.164 format).
         *
         * @return {string|null}
         */
        Body42.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string|null} value 
         */
        Body42.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * Filter calls that were sent from this 10-digit number (E.164 format).
         *
         * @return {string|null}
         */
        Body42.prototype.getFrom = function () {
            return this.from;
        };
    
        /**
         * Setter for From
         * 
         * @param {string|null} value 
         */
        Body42.prototype.setFrom = function (value) {
            this.from = value;
        };
    
        /**
         * Return calls that are from a specified date.
         *
         * @return {string|null}
         */
        Body42.prototype.getDateCreated = function () {
            return this.dateCreated;
        };
    
        /**
         * Setter for DateCreated
         * 
         * @param {string|null} value 
         */
        Body42.prototype.setDateCreated = function (value) {
            this.dateCreated = value;
        };
    
        return Body42;
    }

}(angular));
