/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body2
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body2', ['BaseModel', Body2Model]);

    function Body2Model(BaseModel) {
        var Body2 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.templateId = this.getValue(obj.templateId);
        };

        Body2.prototype = new BaseModel();
        Body2.prototype.constructor = Body2;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body2.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'templateId', realName: 'TemplateId' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body2.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The unique identifier for a template object
         *
         * @return {uuid|string}
         */
        Body2.prototype.getTemplateId = function () {
            return this.templateId;
        };
    
        /**
         * Setter for TemplateId
         * 
         * @param {uuid|string} value 
         */
        Body2.prototype.setTemplateId = function (value) {
            this.templateId = value;
        };
    
        return Body2;
    }

}(angular));
