/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Body35
 *
 * @constructor
 */
angular.module('YtelAPILib')
    .factory('Body35', ['BaseModel', Body35Model]);

    function Body35Model(BaseModel) {
        var Body35 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.subAccountSID = this.getValue(obj.subAccountSID);
            this.activate = this.getValue(obj.activate);
        };

        Body35.prototype = new BaseModel();
        Body35.prototype.constructor = Body35;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Body35.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'subAccountSID', realName: 'SubAccountSID' },
                { name: 'activate', realName: 'Activate' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Body35.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * The SubaccountSid to be activated or suspended
         *
         * @return {string}
         */
        Body35.prototype.getSubAccountSID = function () {
            return this.subAccountSID;
        };
    
        /**
         * Setter for SubAccountSID
         * 
         * @param {string} value 
         */
        Body35.prototype.setSubAccountSID = function (value) {
            this.subAccountSID = value;
        };
    
        /**
         * 0 to suspend or 1 to activate
         *
         * @return {ActivateEnum}
         */
        Body35.prototype.getActivate = function () {
            return this.activate;
        };
    
        /**
         * Setter for Activate
         * 
         * @param {ActivateEnum} value 
         */
        Body35.prototype.setActivate = function (value) {
            this.activate = value;
        };
    
        return Body35;
    }

}(angular));
