/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('NumberType2Enum', [NumberType2EnumModel]);

    function NumberType2EnumModel() {
        return {
            //TODO: Write general description for this element
            ALL: 'all',
    
            //TODO: Write general description for this element
            VOICE: 'voice',
    
            //TODO: Write general description for this element
            SMS: 'sms'
        };
    }

}(angular));
