/**
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('YtelAPILib')
    .factory('Status1Enum', [Status1EnumModel]);

    function Status1EnumModel() {
        return {
            //TODO: Write general description for this element
            CANCELED: 'canceled',
    
            //TODO: Write general description for this element
            COMPLETED: 'completed'
        };
    }

}(angular));
